version: '2'
services:
    equipment-app:
        image: equipment
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://equipment-mysql:3306/equipment?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://equipment-elasticsearch:9200
        ports:
            - 8080:8080
    equipment-mysql:
        extends:
            file: mysql.yml
            service: equipment-mysql
    equipment-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: equipment-elasticsearch
